SELECT DISTINCT ?snumpage ?stitle ?sclass ?s ?p ?o ?oclass ?otitle ?onumpage FROM <%s> {
?d <http://cll.niimm.ksu.ru/ontologies/mocassin#hasSegment> ?s . 
?d <http://cll.niimm.ksu.ru/ontologies/mocassin#hasSegment> ?o .
?s ?p ?o .
?s a ?sclass .
?o a ?oclass .
?s <http://cll.niimm.ksu.ru/ontologies/mocassin#hasStartPageNumber> ?snumpage .
OPTIONAL {
?s <http://cll.niimm.ksu.ru/ontologies/mocassin#hasTitle> ?stitle  .
}
?o <http://cll.niimm.ksu.ru/ontologies/mocassin#hasStartPageNumber> ?onumpage .
OPTIONAL { 
?o <http://cll.niimm.ksu.ru/ontologies/mocassin#hasTitle> ?otitle .} 
FILTER (STR(?d) = "%s") 
FILTER (REGEX(STR(?p), 'ontologies/mocassin'))
}
ORDER BY ?s ?p ?o