SELECT DISTINCT ?snumpage ?sclass ?s ?p ?o ?oclass ?onumpage {
?d <http://cll.niimm.ksu.ru/ontologies/mocassin#hasSegment> ?s . 
?d <http://cll.niimm.ksu.ru/ontologies/mocassin#hasSegment> ?o .
?s ?p ?o .
?s a ?sclass .
?o a ?oclass .
?s <http://cll.niimm.ksu.ru/ontologies/mocassin#hasStartPageNumber> ?snumpage .
?o <http://cll.niimm.ksu.ru/ontologies/mocassin#hasStartPageNumber> ?onumpage .
FILTER (STR(?d) = "%s") 
FILTER (REGEX(STR(?p), 'ontologies/mocassin'))
}
ORDER BY ?s ?p ?o