SELECT * {
?1 a <http://salt.semanticauthoring.org/ontologies/sdo#Publication> .
?1 <http://djpowell.net/schemas/atomrdf/0.3/link> ?2 .
?2 a <http://djpowell.net/schemas/atomrdf/0.3/Link> .
?2 <http://djpowell.net/schemas/atomrdf/0.3/linkType> ?3 .
?2 <http://djpowell.net/schemas/atomrdf/0.3/linkHref> ?4 .
FILTER (str(?1) = "%s") .
}