INSERT INTO GRAPH <http://cll.niimm.ksu.ru/mocassintest> {<http://mathnet.ru/ivm228> <http://djpowell.net/schemas/atomrdf/0.3/title> _:bnode-700053051 .
_:bnode-700053051 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://djpowell.net/schemas/atomrdf/0.3/PlainText> .
<http://mathnet.ru/ivm228> <http://djpowell.net/schemas/atomrdf/0.3/link> _:bnode-700053050 .
_:bnode-700053050 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://djpowell.net/schemas/atomrdf/0.3/Link> .
_:bnode-700053050 <http://djpowell.net/schemas/atomrdf/0.3/linkType> "application/pdf" .
<http://mathnet.ru/ivm228> <http://arxiv.org/schema#id> "ivm228" .
<http://mathnet.ru/ivm228/14043> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasPart> <http://mathnet.ru/ivm228/14179> .
<http://mathnet.ru/ivm228/11808> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://cll.niimm.ksu.ru/ontologies/mocassin#Equation> .
<http://mathnet.ru/ivm228/1623> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasText> "" .
<http://mathnet.ru/ivm228/15989> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasPart> <http://mathnet.ru/ivm228/15990> .
<http://mathnet.ru/ivm228/10654> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasPart> <http://mathnet.ru/ivm228/10655> .
<http://mathnet.ru/ivm228/18898> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasPart> <http://mathnet.ru/ivm228/18899> .
<http://mathnet.ru/ivm228/2409> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasPart> <http://mathnet.ru/ivm228/11924> .
<http://mathnet.ru/ivm228/0> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasPart> <http://mathnet.ru/ivm228/32> .
<http://mathnet.ru/ivm228/17900> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasText> "" .
<http://mathnet.ru/ivm228/3642> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasText> "" .
<http://mathnet.ru/ivm228> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasSegment> <http://mathnet.ru/ivm228/7986> .
<http://mathnet.ru/ivm228/10357> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasTitle> "equation" .
<http://mathnet.ru/ivm228/12648> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasStartPageNumber> "0"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://mathnet.ru/ivm228/11085> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasText> "" .
<http://mathnet.ru/ivm228/14690> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasText> "" .
<http://mathnet.ru/ivm228/8922> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasText> "Лемма Пусть выполнены условия леммы Тогда решение задачи удовлетворяет неравенствам " .
<http://mathnet.ru/ivm228/1508> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasText> "" .
<http://mathnet.ru/ivm228/16205> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasStartPageNumber> "0"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://mathnet.ru/ivm228/13377> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasText> "" .
<http://mathnet.ru/ivm228/10028> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://cll.niimm.ksu.ru/ontologies/mocassin#Equation> .
<http://mathnet.ru/ivm228/2409> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasPart> <http://mathnet.ru/ivm228/12137> .
<http://mathnet.ru/ivm228> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasSegment> <http://mathnet.ru/ivm228/2761> .
<http://mathnet.ru/ivm228> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasSegment> <http://mathnet.ru/ivm228/15151> .
<http://mathnet.ru/ivm228/18785> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasStartPageNumber> "0"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://mathnet.ru/ivm228/6122> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://cll.niimm.ksu.ru/ontologies/mocassin#DocumentSegment> .
<http://mathnet.ru/ivm228/10655> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasTitle> "equation 37" .
<http://mathnet.ru/ivm228/1623> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasTitle> "equation 9" .
<http://mathnet.ru/ivm228/11808> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasTitle> "equation" .
<http://mathnet.ru/ivm228/2593> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasTitle> "Определение 2.1 ." .
<http://mathnet.ru/ivm228/932> <http://cll.niimm.ksu.ru/ontologies/mocassin#hasPart> <http://mathnet.ru/ivm228/1107> .
}
