function viewer(){var O='',vb='" for "gwt:onLoadErrorFn"',tb='" for "gwt:onPropertyErrorFn"',hb='"><\/script>',Y='#',Db='&',Wb='.cache.html',$='/',Vb=':',nb='::',fc='<script defer="defer">viewer.onInjectionDone(\'viewer\')<\/script>',gb='<script id="',dc='<script language="javascript" src="',qb='=',Z='?',sb='Bad handler "',bc='DOMContentLoaded',Ub="GWT module 'viewer' may need to be (re)compiled",ib='SCRIPT',Gb='Unexpected exception in locale detection, using default: ',Fb='_',Eb='__gwt_Locale',fb='__gwt_marker_viewer',jb='base',bb='baseUrl',S='begin',R='bootstrap',ab='clear.cache.gif',pb='content',Bb='default',X='end',Ob='gecko',Pb='gecko1_8',T='gwt.codesvr=',U='gwt.hosted=',V='gwt.hybrid',Xb='gwt/standard/standard.css',ub='gwt:onLoadErrorFn',rb='gwt:onPropertyErrorFn',ob='gwt:property',ac='head',Sb='hosted.html?viewer',_b='href',Nb='ie6',Mb='ie8',wb='iframe',_='img',xb="javascript:''",cc='js/protovis-3.2-PATCHED/protovis-d3.2-PATCHED-COMPRESSED.js',ec='js/protovis-3.2-PATCHED/protovis-d3.2-PATCHED-COMPRESSED.js"><\/script>',Yb='link',Rb='loadExternalRefs',Ab='locale',Cb='locale=',kb='meta',zb='moduleRequested',W='moduleStartup',Lb='msie',lb='name',Ib='opera',yb='position:absolute;width:0;height:0;border:none',Zb='rel',Kb='safari',cb='script',Tb='selectingPermutation',Q='startup',$b='stylesheet',eb='undefined',Qb='unknown',Hb='user.agent',P='viewer',db='viewer.nocache.js',mb='viewer::',Jb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=O,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:S});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(T)!=-1||(c.indexOf(U)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(V)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(P);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return G(a)}}viewer=null;c.gwtOnLoad(y,P,s,x);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:X})}}
function C(){function e(a){var b=a.lastIndexOf(Y);if(b==-1){b=a.length}var c=a.indexOf(Z);if(c==-1){c=a.length}var d=a.lastIndexOf($,Math.min(c,b));return d>=0?a.substring(0,d+1):O}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(_);b.src=a+ab;a=e(b.src)}return a}
function g(){var a=F(bb);if(a!=null){return a}return O}
function h(){var a=m.getElementsByTagName(cb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(db)!=-1){return e(a[b].src)}}return O}
function i(){var a;if(typeof isBodyLoaded==eb||!isBodyLoaded()){var b=fb;var c;m.write(gb+b+hb);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ib){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return O}
function j(){var a=m.getElementsByTagName(jb);if(a.length>0){return a[a.length-1].href}return O}
var k=g();if(k==O){k=h()}if(k==O){k=i()}if(k==O){k=j()}if(k==O){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(kb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(lb),g;if(f){f=f.replace(mb,O);if(f.indexOf(nb)>=0){continue}if(f==ob){g=e.getAttribute(pb);if(g){var h,i=g.indexOf(qb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=O}t[f]=h}}else if(f==rb){g=e.getAttribute(pb);if(g){try{z=eval(g)}catch(a){alert(sb+g+tb)}}}else if(f==ub){g=e.getAttribute(pb);if(g){try{y=eval(g)}catch(a){alert(sb+g+vb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var H;function I(){if(!H){H=true;var a=m.createElement(wb);a.src=xb;a.id=P;a.style.cssText=yb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:zb});a.contentWindow.location.replace(s+K)}}
v[Ab]=function(){var b=null;var c=Bb;try{if(!b){var d=location.search;var e=d.indexOf(Cb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Db,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=F(Ab)}if(!b){b=l[Eb]}if(b){c=b}while(b&&!E(Ab,b)){var h=b.lastIndexOf(Fb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Gb+a)}l[Eb]=c;return b||Bb};u[Ab]={'default':0,ru:1};v[Hb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(b.indexOf(Ib)!=-1){return Ib}else if(b.indexOf(Jb)!=-1){return Kb}else if(b.indexOf(Lb)!=-1){if(document.documentMode>=8){return Mb}else{var d=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){var e=c(d);if(e>=6000){return Nb}}}}else if(b.indexOf(Ob)!=-1){return Pb}return Qb};u[Hb]={gecko1_8:0,ie6:1,ie8:2,opera:3,safari:4};viewer.onScriptLoad=function(){if(H){q=true;B()}};viewer.onInjectionDone=function(){p=true;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Rb,millis:(new Date).getTime(),type:X});B()};D();C();var J;var K;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(P))){l.location.reload();return}K=Sb;J=O}n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:Tb});if(!A()){try{alert(Ub);return;var L=J.indexOf(Vb);if(L!=-1){x=Number(J.substring(L+1));J=J.substring(0,L)}K=J+Wb}catch(a){return}}var M;function N(){if(!r){r=true;if(!__gwt_stylesLoaded[Xb]){var a=m.createElement(Yb);__gwt_stylesLoaded[Xb]=a;a.setAttribute(Zb,$b);a.setAttribute(_b,s+Xb);m.getElementsByTagName(ac)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(bc,N,false)}if(M){clearInterval(M)}}}
if(m.addEventListener){m.addEventListener(bc,function(){I();N()},false)}var M=setInterval(function(){if(/loaded|complete/.test(m.readyState)){I();N()}},50);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:X});n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Rb,millis:(new Date).getTime(),type:S});if(!__gwt_scriptsLoaded[cc]){__gwt_scriptsLoaded[cc]=true;document.write(dc+s+ec)}m.write(fc)}
viewer();