SELECT * {
?1 a <http://www.aktors.org/ontology/portal#Article-Reference> .
?1 <http://www.aktors.org/ontology/portal#has-author> ?2 .
?2 <http://www.aktors.org/ontology/portal#full-name> ?3 .
FILTER (str(?1) = "%s") .
}