SELECT DISTINCT ?s ?p ?o  {
?d <http://cll.niimm.ksu.ru/ontologies/mocassin#hasSegment> ?s . 
?d <http://cll.niimm.ksu.ru/ontologies/mocassin#hasSegment> ?o .
?s ?p ?o .
FILTER (STR(?d) = "%s") 
FILTER (REGEX(STR(?p), 'ontologies/mocassin'))
}