SELECT ?p ?s ?stitle ?snumpage {
OPTIONAL {?s <http://cll.niimm.ksu.ru/ontologies/mocassin#hasTitle> ?stitle } .
?s <http://cll.niimm.ksu.ru/ontologies/mocassin#hasStartPageNumber> ?snumpage .
?p <http://cll.niimm.ksu.ru/ontologies/mocassin#hasSegment> ?s .
FILTER (STR(?s) = "%s") 
}